# Generated by Django 4.1.5 on 2023-03-15 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportScheme',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('importer', models.CharField(editable=False, max_length=255)),
                ('importer_hash', models.CharField(editable=False, max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'File Received')], default=0)),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportSchemeFile',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Uploaded'), (2, 'Inspecting'), (3, 'Inspected'), (4, 'Importing'), (5, 'Imported')], default=0)),
                ('import_scheme', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ml_import_wizard.importscheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportSchemeFileField',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sample', models.TextField(blank=True, null=True)),
                ('import_scheme_file', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ml_import_wizard.importschemefile')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='ImportSchemeItem',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255, verbose_name='App this import item is for')),
                ('model', models.CharField(max_length=255, verbose_name='Model this import item is for')),
                ('field', models.CharField(max_length=255, verbose_name='DB Field this import item is for')),
                ('strategy', models.CharField(max_length=255, null=True, verbose_name='Strategy for doing this import')),
                ('settings', models.JSONField(null=True, verbose_name='Settings specific to this import')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('import_scheme', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ml_import_wizard.importscheme')),
            ],
            options={
                'unique_together': {('app', 'model', 'field')},
            },
        ),
    ]
