# Generated by Django 4.1.5 on 2023-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_import_wizard', '0002_initial_statuses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportSchemeRejectedRows',
            new_name='ImportSchemeRejectedRow',
        ),
    ]
