# Generated by Django 4.1.5 on 2023-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_import_wizard', '0002_initial_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importschemefilefield',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='importschemeitem',
            unique_together={('import_scheme', 'app', 'model', 'field')},
        ),
    ]
