# Generated by Django 4.1.5 on 2023-04-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_import_wizard', '0003_rename_importschemerejectedrows_importschemerejectedrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importschemerejectedrow',
            name='model',
        ),
    ]
