version: '1.0'
services:

  db:
    image: postgres:15.1-alpine

    # ports:
    # - '127.0.0.1:${POSTGRES_PORT}:5432'

    volumes:
      - hiris-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    env_file:
      - .env

  hiris:
    container_name: HIRIS
    build: .
    command: python /hiris/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/hiris
      - hiris-file-storage:/hiris-files

    ports:
      - '127.0.0.1:${WEB_PORT}:8000'

    depends_on:
      - db

    env_file:
      - .env

volumes:
  hiris-db-data:
  hiris-file-storage: