version: '1.0'
services:

  db:
    container_name: HIRIS-DB
    image: postgres:15.3-bullseye

    # Set shared memory size
    shm_size: 1g
    
    ports:
    - "${POSTGRES_PORT}:5432"
     
    volumes:
      - ./postgresql.conf:/config/postgresql.conf
      - hiris-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    env_file:
      - .env

    command: postgres -c config_file='/config/postgresql.conf'

  hiris:
    container_name: HIRIS
    build: .
    command:
      - /bin/bash
      - -c
      - |
        cron
        crontab /hiris/crontab_import_heartbeat
        python /hiris/manage.py runserver 0.0.0.0:${WEB_PORT}

    volumes:
      - .:/hiris
      - hiris-file-storage:/${WORKING_FILES_DIR}

    ports:
      - "${WEB_PORT}:${WEB_PORT}"

    depends_on:
      - db

    env_file:
      - .env

volumes:
  hiris-db-data:
  hiris-file-storage: