version: '0.0'
services:

  db:
    image: postgres:15.1-alpine

   # ports:
   #   - '127.0.0.1:${POSTGRES_PORT}:5432'

    volumes:
      - hiris-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    env_file:
      - .env

  hiris:
    container_name: HIRIS
    build: .
    command: python /hiris/manage.py runserver 0.0.0.0:${WEB_PORT}

    volumes:
      - .:/hiris

    ports:
      - '127.0.0.1:${WEB_PORT}:${WEB_PORT}'

    depends_on:
      - db

    env_file:
      - .env

volumes:
  hiris-db-data: