version: '1.0'
services:

  db:
    container_name: HIRIS-DB
    image: postgres:15.1-alpine

    # Set shared memory size
    shm_size: 1g
    
    # ports:
    # - "${POSTGRES_PORT}:5432"
     
    volumes:
      - hiris-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    env_file:
      - .env

  hiris:
    container_name: HIRIS
    build: .
    command: python /hiris/manage.py runserver 0.0.0.0:${WEB_PORT}

    volumes:
      - .:/hiris
      - hiris-file-storage:/${WORKING_FILES_DIR}

    ports:
      - "${WEB_PORT}:${WEB_PORT}"

    depends_on:
      - db

    env_file:
      - .env

volumes:
  hiris-db-data:
  hiris-file-storage: