# Generated by Django 4.1.5 on 2023-02-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genome_name', models.CharField(max_length=255)),
                ('external_gene_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='GeneType',
            fields=[
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('gene_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gene_type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gene_type',
            },
        ),
        migrations.CreateModel(
            name='GenomeHosts',
            fields=[
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('genome_host_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genome_host_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genome_hosts',
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('genome_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genome_name', models.CharField(max_length=255)),
                ('external_gene_id_name', models.CharField(blank=True, max_length=255, null=True)),
                ('genome_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genomehosts')),
            ],
            options={
                'db_table': 'genome',
            },
        ),
        migrations.CreateModel(
            name='GeneLocation',
            fields=[
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('gene_location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('landmark', models.CharField(max_length=255)),
                ('gene_orientation', models.CharField(choices=[('F', 'Forward'), ('R', 'Reverse')], max_length=1)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gene')),
            ],
            options={
                'db_table': 'gene_location',
            },
        ),
        migrations.AddField(
            model_name='gene',
            name='gene_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genetype'),
        ),
        migrations.AddField(
            model_name='gene',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genome'),
        ),
    ]
