# Generated by Django 4.1.5 on 2023-04-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='gene_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.genetype'),
        ),
    ]
