# Generated by Django 4.1.5 on 2023-05-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integration_integration_ltr_341eb1_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationlocation',
            name='feature_location',
        ),
    ]
