# Generated by Django 4.1.5 on 2023-04-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_daa_set_name_dataset_data_set_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparation',
            name='description',
        ),
        migrations.AddField(
            model_name='preparation',
            name='preparation_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingmethod',
            name='sequencing_method_descripion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetsource',
            name='data_set_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingmethod',
            name='sequencing_method_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
