# Generated by Django 4.1.5 on 2023-04-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_preparation_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationenvironment',
            old_name='integration_envirnment_name',
            new_name='integration_environment_name',
        ),
    ]
