# Generated by Django 4.1.5 on 2023-05-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_integrationlocation_feature_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationFeature',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('integration_feature_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_type_name', models.CharField(max_length=255)),
                ('feature_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.featurelocation')),
                ('integration_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.integrationlocation')),
            ],
            options={
                'db_table': 'integration_features',
            },
        ),
        migrations.AddField(
            model_name='integrationlocation',
            name='feature_locations',
            field=models.ManyToManyField(related_name='integration_locations', through='core.IntegrationFeature', to='core.featurelocation'),
        ),
        migrations.AddIndex(
            model_name='integrationfeature',
            index=models.Index(fields=['integration_location'], name='integration_integra_b01cff_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationfeature',
            index=models.Index(fields=['feature_location'], name='integration_feature_29e154_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationfeature',
            unique_together={('integration_location', 'feature_location')},
        ),
    ]
