# Generated by Django 4.1.5 on 2023-04-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_integration_envirnment_name_integrationenvironment_integration_environment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='ltr',
            field=models.CharField(choices=[('3p', '3p'), ('5p', '5p')], max_length=2, null=True),
        ),
    ]
