# Generated by Django 4.1.5 on 2023-04-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dataset_data_set_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSetSource',
        ),
    ]
