# Generated by Django 4.1.5 on 2023-04-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_datasetsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetSource',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_set_source_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('data_set_source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('revision_data_path', models.TextField(blank=True, null=True)),
                ('revision_data_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('revision_metadata_path', models.TextField(blank=True, null=True)),
                ('revision_metadata_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('revision_git_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('document_name', models.CharField(blank=True, max_length=250, null=True)),
                ('document_pubmed_id', models.IntegerField(blank=True, null=True)),
                ('document_uri', models.TextField(blank=True, null=True)),
                ('document_citation_url', models.TextField(blank=True, null=True)),
                ('document_citation_doi', models.TextField(blank=True, null=True)),
                ('document_citation_issn', models.CharField(blank=True, max_length=255, null=True)),
                ('document_citation_year', models.IntegerField(blank=True, null=True)),
                ('document_citation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('document_citation_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('document_citation_title', models.TextField(blank=True, null=True)),
                ('document_citation_author', models.TextField(blank=True, null=True)),
                ('document_citation_issue_number', models.CharField(blank=True, max_length=255, null=True)),
                ('document_citation_volume', models.IntegerField(blank=True, null=True)),
                ('document_citation_journal', models.TextField(blank=True, null=True)),
                ('document_citation_citekey', models.TextField(blank=True, null=True)),
                ('data_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_set_sources', to='core.dataset')),
            ],
            options={
                'db_table': 'data_set_sources',
            },
        ),
    ]
