# Generated by Django 4.1.5 on 2023-05-24 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_integration_data_set_sampledata_subjectdata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sampledata",
            unique_together={("sample", "key")},
        ),
        migrations.AlterModelTable(
            name="sampledata",
            table="sample_data",
        ),
    ]
