# Generated by Django 4.1.5 on 2023-04-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datasetsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlocation',
            name='feature_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integration_locations', to='core.featurelocation'),
        ),
    ]
