# Generated by Django 4.1.5 on 2023-04-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_integrationlocation_feature_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table='samples',
        ),
    ]
