# Generated by Django 4.1.5 on 2023-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sample_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.integrationenvironment'),
        ),
    ]
