# Generated by Django 4.1.5 on 2023-05-31 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_publicationdata_publication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="pubmed_id",
            new_name="publication_pubmed_id",
        ),
        migrations.AlterUniqueTogether(
            name="publication",
            unique_together={("data_set", "publication_pubmed_id")},
        ),
        migrations.AlterUniqueTogether(
            name="sample",
            unique_together={
                (
                    "subject",
                    "culture",
                    "culture_day",
                    "date",
                    "disease",
                    "genbank",
                    "original_id",
                    "provirus_activity",
                    "replicates",
                    "tissue",
                    "tissue_url",
                    "type",
                    "visit",
                    "years_on_art",
                )
            },
        ),
        migrations.RemoveField(
            model_name="sample",
            name="pubmed_id",
        ),
    ]
