# Generated by Django 4.1.5 on 2023-06-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sample_sample_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set(),
        ),
    ]
