# Generated by Django 4.1.5 on 2023-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_sample_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
    ]
