# Generated by Django 4.1.5 on 2023-06-18 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_integration_breakpoint_sequence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="culture",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="culture_day",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="date",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="genbank",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="original_id",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="provirus_activity",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="replicates",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="tissue",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="tissue_url",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="type",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="visit",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="years_on_art",
        ),
    ]
