# Generated by Django 4.1.5 on 2024-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_dataset_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="ltr",
            field=models.CharField(
                choices=[("3p", "3p"), ("5p", "5p"), ("both", "both")],
                max_length=4,
                null=True,
            ),
        ),
    ]
