# Generated by Django 4.1.5 on 2024-07-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_integration_ltr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationfeature",
            name="integration_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.integrationlocation",
            ),
        ),
    ]
