# Generated by Django 4.1.5 on 2023-02-24 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportScheme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('importer', models.CharField(max_length=255)),
                ('importer_hash', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'File Received')], default=0)),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('import_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='import_wizard.importscheme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
