# Generated by Django 4.1.5 on 2023-02-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSchemeItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('import_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='import_wizard.importscheme')),
                ('import_scheme_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='import_wizard.importschemeitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
